import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FiClock, FiGrid, FiArrowRight, FiDownload, FiFileText } from 'react-icons/fi';
import Image from "next/image";
import jsPDF from "jspdf";
import { API_BASE_URL } from "../config";
import { ProjectCardSkeleton } from "./Skeletons";

interface ProjectSummary {
  id: string;
  title: string;
  updated_at: string;
  thumbnail_url: string | null;
}

interface ProjectData {
   id: string;
   title: string;
   images: Record<number, string>;
   script?: any;
}

interface LibraryViewProps {
  onLoadProject: (id: string) => void;
  onPostToForum: (projectId: string) => void;
}

export default function LibraryView({ onLoadProject, onPostToForum }: LibraryViewProps) {
  const [projects, setProjects] = useState<ProjectSummary[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [exportingId, setExportingId] = useState<string | null>(null);

  useEffect(() => {
    fetchProjects();
  }, []);

    const fetchProjects = async () => {
    try {
      // Create a timeout promise
      const timeoutPromise = new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Request timed out')), 5000)
      );

      const res = await Promise.race([
        fetch(`${API_BASE_URL}/projects`),
        timeoutPromise
      ]) as Response;

      if (res.ok) {
        const data = await res.json();
        setProjects(data);
      }
    } catch (err) {
      console.error("Failed to load projects", err);
      // Optional: Set an error state to show a specific message
    } finally {
      setIsLoading(false);
    }
  };

  const handleExportPDF = async (e: React.MouseEvent, projectId: string, title: string) => {
    e.stopPropagation(); // Prevent opening the project
    setExportingId(projectId);

    try {
        // 1. Fetch full project data to get images
        const res = await fetch(`${API_BASE_URL}/projects/${projectId}`);
        if (!res.ok) throw new Error("Failed to load project data");
        const data: ProjectData = await res.json();
        
        // 2. Initialize PDF
        const doc = new jsPDF({
           orientation: "portrait", 
           unit: "mm", 
           format: "a4"
        });

        // 3. Add Title Page
        doc.setFontSize(24);
        doc.text(title, 20, 40);
        doc.setFontSize(12);
        doc.text(`Generated by Manga Gen`, 20, 50);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 56);
        
        // 4. Add Pages
        const imageIds = Object.keys(data.images).map(Number).sort((a,b) => a - b);
        let yPos = 70;
        
        // Helper to load image
        const loadImage = (url: string) => {
             return new Promise<HTMLImageElement>((resolve, reject) => {
                const img = new window.Image();
                img.crossOrigin = "Anonymous";
                img.onload = () => resolve(img);
                img.onerror = reject;
                img.src = url;
             });
        };

        for (let i = 0; i < imageIds.length; i++) {
           const id = imageIds[i];
           const imageUrl = data.images[id];
           if (!imageUrl) continue;
           
           if (i > 0 && i % 2 === 0) {
              doc.addPage();
              yPos = 20;
           }

           try {
              const img = await loadImage(imageUrl);
              // Calculate ratio to fit A4 width (approx 190mm usable)
              const imgWidth = 170;
              const imgHeight = (img.height / img.width) * imgWidth;
              
              // Check if fits on page, else new page
              if (yPos + imgHeight > 270) {
                 doc.addPage();
                 yPos = 20;
              }
              
              doc.addImage(img, 'PNG', 20, yPos, imgWidth, imgHeight);
              yPos += imgHeight + 10;
              
           } catch (err) {
              console.error(`Failed to add image ${id}`, err);
           }
        }

        // 5. Save
        doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_manga.pdf`);

    } catch (err) {
       console.error(err);
       alert("Failed to export PDF. Please try again.");
    } finally {
       setExportingId(null);
    }
  };

  const formatDate = (isoString: string) => {
    return new Date(isoString).toLocaleDateString(undefined, {
      month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
    });
  };

  /* Loading State */
  if (isLoading) {
    return (
      <div className="max-w-6xl mx-auto pt-10 px-6 pb-20">
         <div className="flex items-center justify-between mb-10">
            <div>
               <h2 className="text-3xl font-black text-gray-900 dark:text-mn-offwhite tracking-tight uppercase">Library</h2>
               <div className="h-4 bg-gray-200 dark:bg-mn-navy/50 rounded w-48 mt-2 animate-pulse" />
            </div>
         </div>
         <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((i) => (
               <ProjectCardSkeleton key={i} />
            ))}
         </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto pt-10 px-6 pb-20">
      <div className="flex items-center justify-between mb-10">
        <div>
           <h2 className="text-3xl font-black text-gray-900 dark:text-mn-offwhite tracking-tight uppercase">Library</h2>
           <p className="text-gray-500 dark:text-mn-offwhite/60 mt-1 font-medium">Manage your saved stories and exports</p>
        </div>
      </div>

      {projects.length === 0 ? (
        <div className="text-center py-24 bg-white dark:bg-mn-blue rounded-3xl border-2 border-dashed border-gray-200 dark:border-mn-teal/20">
          <div className="w-20 h-20 bg-gray-50 dark:bg-mn-navy rounded-full flex items-center justify-center mx-auto mb-6 text-gray-300 dark:text-mn-teal/50 shadow-sm">
            <FiGrid size={32} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-mn-offwhite mb-2">Your library is empty</h3>
          <p className="text-gray-500 dark:text-mn-offwhite/60 mb-8 max-w-sm mx-auto">
             Start your creative journey by generating your first manga chapter.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {projects.map((project, index) => (
            <motion.div
              key={project.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="group bg-white dark:bg-mn-blue border border-gray-200 dark:border-mn-teal/20 rounded-2xl overflow-hidden shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all cursor-pointer flex flex-col"
              onClick={() => onLoadProject(project.id)}
            >
              {/* Thumbnail Area */}
              <div className="aspect-[3/4] bg-gray-100 dark:bg-mn-navy relative overflow-hidden">
                {project.thumbnail_url ? (
                  <Image 
                    src={project.thumbnail_url} 
                    alt={project.title} 
                    fill 
                    className="object-cover transition-transform duration-700 group-hover:scale-105"
                    unoptimized
                  />
                ) : (
                  <div className="absolute inset-0 flex items-center justify-center text-gray-300 dark:text-mn-teal/20">
                     <FiGrid size={40} />
                  </div>
                )}
                
                {/* Hover Overlay */}
                <div className="absolute inset-0 bg-mn-navy/60 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center gap-3 backdrop-blur-[2px]">
                   <span className="bg-mn-offwhite text-mn-navy px-5 py-2 rounded-full font-bold text-sm transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300 shadow-lg">
                      Open Editor
                   </span>
                </div>
              </div>

              {/* Info Area */}
              <div className="p-5 flex-1 flex flex-col">
                <h3 className="font-bold text-gray-900 dark:text-mn-offwhite truncate mb-1 text-lg">{project.title}</h3>
                <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-mn-offwhite/60 mb-4 font-medium">
                  <FiClock size={12} /> 
                  <span>Updated {formatDate(project.updated_at)}</span>
                </div>
                
                <div className="mt-auto pt-4 border-t border-gray-100 dark:border-mn-navy/20 flex justify-between items-center gap-2">
                   {/* Share Button */}
                   <button
                        onClick={(e) => { e.stopPropagation(); onPostToForum(project.id); }}
                        className="flex-1 flex items-center justify-center gap-1.5 text-xs font-bold text-mn-offwhite bg-mn-teal hover:bg-mn-teal/90 py-2 rounded-lg transition-colors uppercase tracking-wide"
                   >
                        Share
                   </button>

                   {/* PDF Button */}
                   <button 
                      onClick={(e) => handleExportPDF(e, project.id, project.title)}
                      disabled={exportingId === project.id}
                      className="p-2 text-mn-teal bg-mn-teal/10 hover:bg-mn-teal/20 rounded-lg transition-colors disabled:opacity-50"
                      title="Export PDF"
                   >
                      {exportingId === project.id ? (
                        <div className="w-4 h-4 border-2 border-current border-t-transparent animate-spin" />
                      ) : (
                        <FiDownload size={16} />
                      )}
                   </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
