import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FiClock, FiGrid, FiArrowRight, FiDownload, FiFileText } from 'react-icons/fi';
import Image from "next/image";
import jsPDF from "jspdf";

interface ProjectSummary {
  id: string;
  title: string;
  updated_at: string;
  thumbnail_url: string | null;
}

interface ProjectData {
   id: string;
   title: string;
   images: Record<number, string>;
   script?: any;
}

interface LibraryViewProps {
  onLoadProject: (id: string) => void;
}

export default function LibraryView({ onLoadProject }: LibraryViewProps) {
  const [projects, setProjects] = useState<ProjectSummary[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [exportingId, setExportingId] = useState<string | null>(null);

  useEffect(() => {
    fetchProjects();
  }, []);

  const fetchProjects = async () => {
    try {
      const res = await fetch('http://localhost:8000/projects');
      if (res.ok) {
        const data = await res.json();
        setProjects(data);
      }
    } catch (err) {
      console.error("Failed to load projects", err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleExportPDF = async (e: React.MouseEvent, projectId: string, title: string) => {
    e.stopPropagation(); // Prevent opening the project
    setExportingId(projectId);

    try {
        // 1. Fetch full project data to get images
        const res = await fetch(`http://localhost:8000/projects/${projectId}`);
        if (!res.ok) throw new Error("Failed to load project data");
        const data: ProjectData = await res.json();
        
        // 2. Initialize PDF
        const doc = new jsPDF({
           orientation: "portrait", 
           unit: "mm", 
           format: "a4"
        });

        // 3. Add Title Page
        doc.setFontSize(24);
        doc.text(title, 20, 40);
        doc.setFontSize(12);
        doc.text(`Generated by Manga Gen`, 20, 50);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 56);
        
        // 4. Add Pages
        const imageIds = Object.keys(data.images).map(Number).sort((a,b) => a - b);
        let yPos = 70;
        
        // Helper to load image
        const loadImage = (url: string) => {
             return new Promise<HTMLImageElement>((resolve, reject) => {
                const img = new window.Image();
                img.crossOrigin = "Anonymous";
                img.onload = () => resolve(img);
                img.onerror = reject;
                img.src = url;
             });
        };

        for (let i = 0; i < imageIds.length; i++) {
           const id = imageIds[i];
           const imageUrl = data.images[id];
           if (!imageUrl) continue;
           
           if (i > 0 && i % 2 === 0) {
              doc.addPage();
              yPos = 20;
           }

           try {
              const img = await loadImage(imageUrl);
              // Calculate ratio to fit A4 width (approx 190mm usable)
              const imgWidth = 170;
              const imgHeight = (img.height / img.width) * imgWidth;
              
              // Check if fits on page, else new page
              if (yPos + imgHeight > 270) {
                 doc.addPage();
                 yPos = 20;
              }
              
              doc.addImage(img, 'PNG', 20, yPos, imgWidth, imgHeight);
              yPos += imgHeight + 10;
              
           } catch (err) {
              console.error(`Failed to add image ${id}`, err);
           }
        }

        // 5. Save
        doc.save(`${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_manga.pdf`);

    } catch (err) {
       console.error(err);
       alert("Failed to export PDF. Please try again.");
    } finally {
       setExportingId(null);
    }
  };

  const formatDate = (isoString: string) => {
    return new Date(isoString).toLocaleDateString(undefined, {
      month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
    });
  };

  if (isLoading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
         <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 dark:border-white"></div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto pt-10 px-6 pb-20">
      <div className="flex items-center justify-between mb-10">
        <div>
           <h2 className="text-3xl font-bold text-gray-900 dark:text-white tracking-tight">Library</h2>
           <p className="text-gray-500 dark:text-gray-400 mt-1">Manage your saved stories and exports</p>
        </div>
      </div>

      {projects.length === 0 ? (
        <div className="text-center py-24 bg-zinc-50 dark:bg-zinc-950/50 rounded-3xl border border-dashed border-zinc-200 dark:border-zinc-800">
          <div className="w-20 h-20 bg-white dark:bg-zinc-900 rounded-full flex items-center justify-center mx-auto mb-6 text-gray-300 dark:text-zinc-700 shadow-sm">
            <FiGrid size={32} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Your library is empty</h3>
          <p className="text-gray-500 dark:text-gray-400 mb-8 max-w-sm mx-auto">
             Start your creative journey by generating your first manga chapter.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {projects.map((project, index) => (
            <motion.div
              key={project.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="group bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-2xl overflow-hidden shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all cursor-pointer flex flex-col"
              onClick={() => onLoadProject(project.id)}
            >
              {/* Thumbnail Area */}
              <div className="aspect-[3/4] bg-gray-100 dark:bg-zinc-950 relative overflow-hidden">
                {project.thumbnail_url ? (
                  <Image 
                    src={project.thumbnail_url} 
                    alt={project.title} 
                    fill 
                    className="object-cover transition-transform duration-700 group-hover:scale-105"
                    unoptimized
                  />
                ) : (
                  <div className="absolute inset-0 flex items-center justify-center text-gray-300 dark:text-zinc-800">
                     <FiGrid size={40} />
                  </div>
                )}
                
                {/* Hover Overlay */}
                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2 backdrop-blur-[2px]">
                   <span className="bg-white text-black px-4 py-2 rounded-full font-bold text-sm transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
                      Open Editor
                   </span>
                </div>
              </div>

              {/* Info Area */}
              <div className="p-5 flex-1 flex flex-col">
                <h3 className="font-bold text-gray-900 dark:text-white truncate mb-1 text-lg">{project.title}</h3>
                <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400 mb-4">
                  <FiClock size={12} /> 
                  <span>Updated {formatDate(project.updated_at)}</span>
                </div>
                
                <div className="mt-auto pt-4 border-t border-gray-100 dark:border-zinc-800 flex justify-between items-center">
                   <button 
                      className="text-xs font-semibold text-gray-500 hover:text-gray-900 dark:hover:text-white transition-colors"
                      onClick={(e) => { e.stopPropagation(); onLoadProject(project.id); }}
                   >
                      Edit
                   </button>
                   
                   <button 
                      onClick={(e) => handleExportPDF(e, project.id, project.title)}
                      disabled={exportingId === project.id}
                      className="flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 bg-blue-50 dark:bg-blue-900/20 px-3 py-1.5 rounded-full transition-colors disabled:opacity-50"
                   >
                      {exportingId === project.id ? (
                        <>Loading...</>
                      ) : (
                        <>
                           <FiDownload size={14} />
                           PDF
                        </>
                      )}
                   </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
